# Generated by Django 2.0 on 2017-12-14 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0002_myuser_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='verified'),
        ),
    ]
